# Generated by Django 6.0.4 on 2026-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='high', max_length=10),
        ),
    ]
